workflows:
  android:
    name: Build Android APK
    max_build_duration: 15
    environment:
      java: 17
    scripts:
      - ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
